/**
 * Generates public/probe.obj — the deep-space probe that flies the spline tour
 * in chapter 2, in the lineage of the shuttle.obj from the 2015 matrices
 * assignment.
 *
 * Authored as a script rather than by hand so the shape stays editable, but the
 * committed .obj is a real asset parsed by our own loader at runtime.
 *
 *   node tools/make-probe.mjs
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../public/probe.obj');

const vertices = [];
const faces = [];

/** Push a vertex, returning its 1-based OBJ index. */
function vertex(x, y, z) {
  vertices.push([x, y, z]);
  return vertices.length;
}

function face(...indices) {
  faces.push(indices);
}

/** Ring of points on a circle in the XY plane at depth z. */
function ring(radius, z, sides, rotate = 0) {
  const out = [];
  for (let i = 0; i < sides; i++) {
    const a = rotate + (i / sides) * Math.PI * 2;
    out.push(vertex(Math.cos(a) * radius, Math.sin(a) * radius, z));
  }
  return out;
}

/** Connect two equal-length rings with quads. */
function bridge(a, b) {
  for (let i = 0; i < a.length; i++) {
    const j = (i + 1) % a.length;
    face(a[i], a[j], b[j], b[i]);
  }
}

/** Cap a ring with a fan through a centre point. */
function cap(ringIndices, z, flip = false) {
  const centre = vertex(0, 0, z);
  for (let i = 0; i < ringIndices.length; i++) {
    const j = (i + 1) % ringIndices.length;
    if (flip) face(centre, ringIndices[j], ringIndices[i]);
    else face(centre, ringIndices[i], ringIndices[j]);
  }
}

function box(cx, cy, cz, hx, hy, hz) {
  const v = [
    vertex(cx - hx, cy - hy, cz - hz), vertex(cx + hx, cy - hy, cz - hz),
    vertex(cx + hx, cy + hy, cz - hz), vertex(cx - hx, cy + hy, cz - hz),
    vertex(cx - hx, cy - hy, cz + hz), vertex(cx + hx, cy - hy, cz + hz),
    vertex(cx + hx, cy + hy, cz + hz), vertex(cx - hx, cy + hy, cz + hz),
  ];
  face(v[0], v[3], v[2], v[1]); // back
  face(v[4], v[5], v[6], v[7]); // front
  face(v[0], v[1], v[5], v[4]); // bottom
  face(v[2], v[3], v[7], v[6]); // top
  face(v[1], v[2], v[6], v[5]); // right
  face(v[0], v[4], v[7], v[3]); // left
}

/** A cylinder along Z from z0 to z1. */
function cylinder(radius, z0, z1, sides) {
  const a = ring(radius, z0, sides);
  const b = ring(radius, z1, sides);
  bridge(a, b);
  cap(a, z0, true);
  cap(b, z1, false);
}

// --- The probe. +Z is "forward", the direction of travel. ------------------

const DISH_SIDES = 24;
const BUS_SIDES = 10;

// High-gain antenna: a shallow parabolic dish facing forward, built as three
// concentric rings so the curve survives flat shading.
const dishRim = ring(0.62, 0.34, DISH_SIDES);
const dishMid = ring(0.40, 0.20, DISH_SIDES);
const dishInner = ring(0.18, 0.12, DISH_SIDES);
bridge(dishRim, dishMid);
bridge(dishMid, dishInner);
cap(dishInner, 0.09, false);
// Back of the dish, so it is solid from behind.
const dishBack = ring(0.62, 0.30, DISH_SIDES);
bridge(dishBack, dishRim);
cap(dishBack, 0.26, true);

// Feed horn on a short tripod-free mast.
cylinder(0.045, 0.34, 0.62, 8);
cylinder(0.09, 0.62, 0.70, 8);

// The bus: a ten-sided drum behind the dish.
const busFront = ring(0.26, 0.04, BUS_SIDES);
const busBack = ring(0.26, -0.24, BUS_SIDES);
bridge(busFront, busBack);
cap(busFront, 0.04, false);
cap(busBack, -0.24, true);

// Radioisotope generators on a boom out to -X.
cylinder(0.028, -0.10, -0.11, 6); // stub, keeps the boom attached visually
box(-0.52, 0.0, -0.10, 0.28, 0.075, 0.075);
box(-0.86, 0.0, -0.10, 0.10, 0.10, 0.10);

// Magnetometer boom out to +X.
box(0.62, 0.0, -0.08, 0.40, 0.018, 0.018);
box(1.06, 0.0, -0.08, 0.05, 0.05, 0.05);

// Instrument scan platform, slung below.
box(0.10, -0.34, -0.02, 0.14, 0.10, 0.14);

// Main engine bell at the rear.
const bellFront = ring(0.10, -0.24, 12);
const bellBack = ring(0.20, -0.46, 12);
bridge(bellFront, bellBack);
cap(bellBack, -0.50, true);

const lines = [
  '# The Forge — chapter 02 probe',
  '# Generated by tools/make-probe.mjs. +Z is forward.',
  `# ${vertices.length} vertices, ${faces.length} faces`,
  'o probe',
];

for (const [x, y, z] of vertices) {
  lines.push(`v ${x.toFixed(5)} ${y.toFixed(5)} ${z.toFixed(5)}`);
}
for (const f of faces) {
  lines.push(`f ${f.join(' ')}`);
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n') + '\n');

console.log(`wrote ${outPath}: ${vertices.length} vertices, ${faces.length} faces`);
